### Home
GET http://localhost:5000/

### Obtener Productos
GET http://localhost:5000/productos
Authorization: hola-mundo

### Filtrar Productos
GET http://localhost:5000/productos?filtro=abc
Authorization: hola-mundo

### Productos
POST http://localhost:5000/productos
Content-Type: application/json

{
    "nombre": "abc",
    "cantidad": 5,
    "precio": 200
}

### Cambiar Productos
PUT http://localhost:5000/productos/6
Content-Type: application/json

{
    "nombre": "Producto CB",
    "cantidad": 10,
    "precio": 10
}


### Eliminar Producto
DELETE http://localhost:5000/productos/2

### Get Producto
GET http://localhost:5000/productos/3
